apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web-deployment
  replicas: 4
  template:
    metadata:
      name: web-pod
      labels:
        app: web-deployment
    spec:
      containers:
      - name: web-deployment
        image: dileep95/spring:tagVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
