apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web-deployment
spec:
  containers:
    - name: web-deployment
      image: dileep95/spring:tagVersion
      imagePullPolicy: Always
      ports:
      - containerPort: 8090
